export const Roles = {
    OWNER: "OWNER",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
}

export const Permissions = {
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  MANAGE_WORKSPACE_SETTINGS: "MANAGE_WORKSPACE_SETTINGS",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",

  ADD_MEMBER: "ADD_MEMBER",
  CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",
  REMOVE_MEMBER: "REMOVE_MEMBER",

  USE_DOCS: "USE_DOCS",
  EDIT_DOCS: "EDIT_DOCS",

  USE_WHITEBOARD: "USE_WHITEBOARD",
  EDIT_WHITEBOARD: "EDIT_WHITEBOARD",

  USE_CODE_EDITOR: "USE_CODE_EDITOR",
  EDIT_CODE_EDITOR: "EDIT_CODE_EDITOR",

  VIEW_ONLY: "VIEW_ONLY",
}